/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XocDiaJun88RouteImport } from './routes/xoc-dia-jun88'
import { Route as XocDiaBipRouteImport } from './routes/xoc-dia-bip'
import { Route as XoSoRouteImport } from './routes/xo-so'
import { Route as VanHoaDoanhNghiepRouteImport } from './routes/van-hoa-doanh-nghiep'
import { Route as UuDaiRouteImport } from './routes/uu-dai'
import { Route as TuyenDungRouteImport } from './routes/tuyen-dung'
import { Route as TheThaoRouteImport } from './routes/the-thao'
import { Route as TaiXiuJun88RouteImport } from './routes/tai-xiu-jun88'
import { Route as TaiXiuRouteImport } from './routes/tai-xiu'
import { Route as TaiAppJun88RouteImport } from './routes/tai-app-jun88'
import { Route as SuKienRouteImport } from './routes/su-kien'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RutTienJun88RouteImport } from './routes/rut-tien-jun88'
import { Route as RouletteJun88RouteImport } from './routes/roulette-jun88'
import { Route as RongHoOnlineRouteImport } from './routes/rong-ho-online'
import { Route as RongHoJun88RouteImport } from './routes/rong-ho-jun88'
import { Route as RakeLaGiTrongPokerRouteImport } from './routes/rake-la-gi-trong-poker'
import { Route as PokerOnlineRouteImport } from './routes/poker-online'
import { Route as PokerJun88RouteImport } from './routes/poker-jun88'
import { Route as NoHuRouteImport } from './routes/no-hu'
import { Route as NapTienJun88RouteImport } from './routes/nap-tien-jun88'
import { Route as LienHeVoiChungToiRouteImport } from './routes/lien-he-voi-chung-toi'
import { Route as LienHeJun88RouteImport } from './routes/lien-he-jun88'
import { Route as KhuyenMaiRouteImport } from './routes/khuyen-mai'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as GiaiDenLoDeRouteImport } from './routes/giai-den-lo-de'
import { Route as EsportRouteImport } from './routes/esport'
import { Route as DieuKhoanDichVuRouteImport } from './routes/dieu-khoan-dich-vu'
import { Route as DangNhapJun88RouteImport } from './routes/dang-nhap-jun88'
import { Route as DangKyJun88RouteImport } from './routes/dang-ky-jun88'
import { Route as ChinhSachQuyenRiengTuRouteImport } from './routes/chinh-sach-quyen-rieng-tu'
import { Route as CasinoJun88RouteImport } from './routes/casino-jun88'
import { Route as CasinoRouteImport } from './routes/casino'
import { Route as CachTinhDiemLoRouteImport } from './routes/cach-tinh-diem-lo'
import { Route as BlackjackJun88RouteImport } from './routes/blackjack-jun88'
import { Route as BaoLoLaGiRouteImport } from './routes/bao-lo-la-gi'
import { Route as BaccaratOnlineRouteImport } from './routes/baccarat-online'
import { Route as BaccaratJun88RouteImport } from './routes/baccarat-jun88'
import { Route as IndexRouteImport } from './routes/index'

const XocDiaJun88Route = XocDiaJun88RouteImport.update({
  id: '/xoc-dia-jun88',
  path: '/xoc-dia-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const XocDiaBipRoute = XocDiaBipRouteImport.update({
  id: '/xoc-dia-bip',
  path: '/xoc-dia-bip',
  getParentRoute: () => rootRouteImport,
} as any)
const XoSoRoute = XoSoRouteImport.update({
  id: '/xo-so',
  path: '/xo-so',
  getParentRoute: () => rootRouteImport,
} as any)
const VanHoaDoanhNghiepRoute = VanHoaDoanhNghiepRouteImport.update({
  id: '/van-hoa-doanh-nghiep',
  path: '/van-hoa-doanh-nghiep',
  getParentRoute: () => rootRouteImport,
} as any)
const UuDaiRoute = UuDaiRouteImport.update({
  id: '/uu-dai',
  path: '/uu-dai',
  getParentRoute: () => rootRouteImport,
} as any)
const TuyenDungRoute = TuyenDungRouteImport.update({
  id: '/tuyen-dung',
  path: '/tuyen-dung',
  getParentRoute: () => rootRouteImport,
} as any)
const TheThaoRoute = TheThaoRouteImport.update({
  id: '/the-thao',
  path: '/the-thao',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiXiuJun88Route = TaiXiuJun88RouteImport.update({
  id: '/tai-xiu-jun88',
  path: '/tai-xiu-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiXiuRoute = TaiXiuRouteImport.update({
  id: '/tai-xiu',
  path: '/tai-xiu',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiAppJun88Route = TaiAppJun88RouteImport.update({
  id: '/tai-app-jun88',
  path: '/tai-app-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const SuKienRoute = SuKienRouteImport.update({
  id: '/su-kien',
  path: '/su-kien',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RutTienJun88Route = RutTienJun88RouteImport.update({
  id: '/rut-tien-jun88',
  path: '/rut-tien-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const RouletteJun88Route = RouletteJun88RouteImport.update({
  id: '/roulette-jun88',
  path: '/roulette-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const RongHoOnlineRoute = RongHoOnlineRouteImport.update({
  id: '/rong-ho-online',
  path: '/rong-ho-online',
  getParentRoute: () => rootRouteImport,
} as any)
const RongHoJun88Route = RongHoJun88RouteImport.update({
  id: '/rong-ho-jun88',
  path: '/rong-ho-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const RakeLaGiTrongPokerRoute = RakeLaGiTrongPokerRouteImport.update({
  id: '/rake-la-gi-trong-poker',
  path: '/rake-la-gi-trong-poker',
  getParentRoute: () => rootRouteImport,
} as any)
const PokerOnlineRoute = PokerOnlineRouteImport.update({
  id: '/poker-online',
  path: '/poker-online',
  getParentRoute: () => rootRouteImport,
} as any)
const PokerJun88Route = PokerJun88RouteImport.update({
  id: '/poker-jun88',
  path: '/poker-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const NoHuRoute = NoHuRouteImport.update({
  id: '/no-hu',
  path: '/no-hu',
  getParentRoute: () => rootRouteImport,
} as any)
const NapTienJun88Route = NapTienJun88RouteImport.update({
  id: '/nap-tien-jun88',
  path: '/nap-tien-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeVoiChungToiRoute = LienHeVoiChungToiRouteImport.update({
  id: '/lien-he-voi-chung-toi',
  path: '/lien-he-voi-chung-toi',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeJun88Route = LienHeJun88RouteImport.update({
  id: '/lien-he-jun88',
  path: '/lien-he-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const KhuyenMaiRoute = KhuyenMaiRouteImport.update({
  id: '/khuyen-mai',
  path: '/khuyen-mai',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaiDenLoDeRoute = GiaiDenLoDeRouteImport.update({
  id: '/giai-den-lo-de',
  path: '/giai-den-lo-de',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportRoute = EsportRouteImport.update({
  id: '/esport',
  path: '/esport',
  getParentRoute: () => rootRouteImport,
} as any)
const DieuKhoanDichVuRoute = DieuKhoanDichVuRouteImport.update({
  id: '/dieu-khoan-dich-vu',
  path: '/dieu-khoan-dich-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapJun88Route = DangNhapJun88RouteImport.update({
  id: '/dang-nhap-jun88',
  path: '/dang-nhap-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyJun88Route = DangKyJun88RouteImport.update({
  id: '/dang-ky-jun88',
  path: '/dang-ky-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachQuyenRiengTuRoute = ChinhSachQuyenRiengTuRouteImport.update({
  id: '/chinh-sach-quyen-rieng-tu',
  path: '/chinh-sach-quyen-rieng-tu',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoJun88Route = CasinoJun88RouteImport.update({
  id: '/casino-jun88',
  path: '/casino-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoRoute = CasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => rootRouteImport,
} as any)
const CachTinhDiemLoRoute = CachTinhDiemLoRouteImport.update({
  id: '/cach-tinh-diem-lo',
  path: '/cach-tinh-diem-lo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackjackJun88Route = BlackjackJun88RouteImport.update({
  id: '/blackjack-jun88',
  path: '/blackjack-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoLoLaGiRoute = BaoLoLaGiRouteImport.update({
  id: '/bao-lo-la-gi',
  path: '/bao-lo-la-gi',
  getParentRoute: () => rootRouteImport,
} as any)
const BaccaratOnlineRoute = BaccaratOnlineRouteImport.update({
  id: '/baccarat-online',
  path: '/baccarat-online',
  getParentRoute: () => rootRouteImport,
} as any)
const BaccaratJun88Route = BaccaratJun88RouteImport.update({
  id: '/baccarat-jun88',
  path: '/baccarat-jun88',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baccarat-jun88': typeof BaccaratJun88Route
  '/baccarat-online': typeof BaccaratOnlineRoute
  '/bao-lo-la-gi': typeof BaoLoLaGiRoute
  '/blackjack-jun88': typeof BlackjackJun88Route
  '/cach-tinh-diem-lo': typeof CachTinhDiemLoRoute
  '/casino': typeof CasinoRoute
  '/casino-jun88': typeof CasinoJun88Route
  '/chinh-sach-quyen-rieng-tu': typeof ChinhSachQuyenRiengTuRoute
  '/dang-ky-jun88': typeof DangKyJun88Route
  '/dang-nhap-jun88': typeof DangNhapJun88Route
  '/dieu-khoan-dich-vu': typeof DieuKhoanDichVuRoute
  '/esport': typeof EsportRoute
  '/giai-den-lo-de': typeof GiaiDenLoDeRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/khuyen-mai': typeof KhuyenMaiRoute
  '/lien-he-jun88': typeof LienHeJun88Route
  '/lien-he-voi-chung-toi': typeof LienHeVoiChungToiRoute
  '/nap-tien-jun88': typeof NapTienJun88Route
  '/no-hu': typeof NoHuRoute
  '/poker-jun88': typeof PokerJun88Route
  '/poker-online': typeof PokerOnlineRoute
  '/rake-la-gi-trong-poker': typeof RakeLaGiTrongPokerRoute
  '/rong-ho-jun88': typeof RongHoJun88Route
  '/rong-ho-online': typeof RongHoOnlineRoute
  '/roulette-jun88': typeof RouletteJun88Route
  '/rut-tien-jun88': typeof RutTienJun88Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/su-kien': typeof SuKienRoute
  '/tai-app-jun88': typeof TaiAppJun88Route
  '/tai-xiu': typeof TaiXiuRoute
  '/tai-xiu-jun88': typeof TaiXiuJun88Route
  '/the-thao': typeof TheThaoRoute
  '/tuyen-dung': typeof TuyenDungRoute
  '/uu-dai': typeof UuDaiRoute
  '/van-hoa-doanh-nghiep': typeof VanHoaDoanhNghiepRoute
  '/xo-so': typeof XoSoRoute
  '/xoc-dia-bip': typeof XocDiaBipRoute
  '/xoc-dia-jun88': typeof XocDiaJun88Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baccarat-jun88': typeof BaccaratJun88Route
  '/baccarat-online': typeof BaccaratOnlineRoute
  '/bao-lo-la-gi': typeof BaoLoLaGiRoute
  '/blackjack-jun88': typeof BlackjackJun88Route
  '/cach-tinh-diem-lo': typeof CachTinhDiemLoRoute
  '/casino': typeof CasinoRoute
  '/casino-jun88': typeof CasinoJun88Route
  '/chinh-sach-quyen-rieng-tu': typeof ChinhSachQuyenRiengTuRoute
  '/dang-ky-jun88': typeof DangKyJun88Route
  '/dang-nhap-jun88': typeof DangNhapJun88Route
  '/dieu-khoan-dich-vu': typeof DieuKhoanDichVuRoute
  '/esport': typeof EsportRoute
  '/giai-den-lo-de': typeof GiaiDenLoDeRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/khuyen-mai': typeof KhuyenMaiRoute
  '/lien-he-jun88': typeof LienHeJun88Route
  '/lien-he-voi-chung-toi': typeof LienHeVoiChungToiRoute
  '/nap-tien-jun88': typeof NapTienJun88Route
  '/no-hu': typeof NoHuRoute
  '/poker-jun88': typeof PokerJun88Route
  '/poker-online': typeof PokerOnlineRoute
  '/rake-la-gi-trong-poker': typeof RakeLaGiTrongPokerRoute
  '/rong-ho-jun88': typeof RongHoJun88Route
  '/rong-ho-online': typeof RongHoOnlineRoute
  '/roulette-jun88': typeof RouletteJun88Route
  '/rut-tien-jun88': typeof RutTienJun88Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/su-kien': typeof SuKienRoute
  '/tai-app-jun88': typeof TaiAppJun88Route
  '/tai-xiu': typeof TaiXiuRoute
  '/tai-xiu-jun88': typeof TaiXiuJun88Route
  '/the-thao': typeof TheThaoRoute
  '/tuyen-dung': typeof TuyenDungRoute
  '/uu-dai': typeof UuDaiRoute
  '/van-hoa-doanh-nghiep': typeof VanHoaDoanhNghiepRoute
  '/xo-so': typeof XoSoRoute
  '/xoc-dia-bip': typeof XocDiaBipRoute
  '/xoc-dia-jun88': typeof XocDiaJun88Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baccarat-jun88': typeof BaccaratJun88Route
  '/baccarat-online': typeof BaccaratOnlineRoute
  '/bao-lo-la-gi': typeof BaoLoLaGiRoute
  '/blackjack-jun88': typeof BlackjackJun88Route
  '/cach-tinh-diem-lo': typeof CachTinhDiemLoRoute
  '/casino': typeof CasinoRoute
  '/casino-jun88': typeof CasinoJun88Route
  '/chinh-sach-quyen-rieng-tu': typeof ChinhSachQuyenRiengTuRoute
  '/dang-ky-jun88': typeof DangKyJun88Route
  '/dang-nhap-jun88': typeof DangNhapJun88Route
  '/dieu-khoan-dich-vu': typeof DieuKhoanDichVuRoute
  '/esport': typeof EsportRoute
  '/giai-den-lo-de': typeof GiaiDenLoDeRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/khuyen-mai': typeof KhuyenMaiRoute
  '/lien-he-jun88': typeof LienHeJun88Route
  '/lien-he-voi-chung-toi': typeof LienHeVoiChungToiRoute
  '/nap-tien-jun88': typeof NapTienJun88Route
  '/no-hu': typeof NoHuRoute
  '/poker-jun88': typeof PokerJun88Route
  '/poker-online': typeof PokerOnlineRoute
  '/rake-la-gi-trong-poker': typeof RakeLaGiTrongPokerRoute
  '/rong-ho-jun88': typeof RongHoJun88Route
  '/rong-ho-online': typeof RongHoOnlineRoute
  '/roulette-jun88': typeof RouletteJun88Route
  '/rut-tien-jun88': typeof RutTienJun88Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/su-kien': typeof SuKienRoute
  '/tai-app-jun88': typeof TaiAppJun88Route
  '/tai-xiu': typeof TaiXiuRoute
  '/tai-xiu-jun88': typeof TaiXiuJun88Route
  '/the-thao': typeof TheThaoRoute
  '/tuyen-dung': typeof TuyenDungRoute
  '/uu-dai': typeof UuDaiRoute
  '/van-hoa-doanh-nghiep': typeof VanHoaDoanhNghiepRoute
  '/xo-so': typeof XoSoRoute
  '/xoc-dia-bip': typeof XocDiaBipRoute
  '/xoc-dia-jun88': typeof XocDiaJun88Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baccarat-jun88'
    | '/baccarat-online'
    | '/bao-lo-la-gi'
    | '/blackjack-jun88'
    | '/cach-tinh-diem-lo'
    | '/casino'
    | '/casino-jun88'
    | '/chinh-sach-quyen-rieng-tu'
    | '/dang-ky-jun88'
    | '/dang-nhap-jun88'
    | '/dieu-khoan-dich-vu'
    | '/esport'
    | '/giai-den-lo-de'
    | '/gioi-thieu'
    | '/khuyen-mai'
    | '/lien-he-jun88'
    | '/lien-he-voi-chung-toi'
    | '/nap-tien-jun88'
    | '/no-hu'
    | '/poker-jun88'
    | '/poker-online'
    | '/rake-la-gi-trong-poker'
    | '/rong-ho-jun88'
    | '/rong-ho-online'
    | '/roulette-jun88'
    | '/rut-tien-jun88'
    | '/sitemap.xml'
    | '/su-kien'
    | '/tai-app-jun88'
    | '/tai-xiu'
    | '/tai-xiu-jun88'
    | '/the-thao'
    | '/tuyen-dung'
    | '/uu-dai'
    | '/van-hoa-doanh-nghiep'
    | '/xo-so'
    | '/xoc-dia-bip'
    | '/xoc-dia-jun88'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baccarat-jun88'
    | '/baccarat-online'
    | '/bao-lo-la-gi'
    | '/blackjack-jun88'
    | '/cach-tinh-diem-lo'
    | '/casino'
    | '/casino-jun88'
    | '/chinh-sach-quyen-rieng-tu'
    | '/dang-ky-jun88'
    | '/dang-nhap-jun88'
    | '/dieu-khoan-dich-vu'
    | '/esport'
    | '/giai-den-lo-de'
    | '/gioi-thieu'
    | '/khuyen-mai'
    | '/lien-he-jun88'
    | '/lien-he-voi-chung-toi'
    | '/nap-tien-jun88'
    | '/no-hu'
    | '/poker-jun88'
    | '/poker-online'
    | '/rake-la-gi-trong-poker'
    | '/rong-ho-jun88'
    | '/rong-ho-online'
    | '/roulette-jun88'
    | '/rut-tien-jun88'
    | '/sitemap.xml'
    | '/su-kien'
    | '/tai-app-jun88'
    | '/tai-xiu'
    | '/tai-xiu-jun88'
    | '/the-thao'
    | '/tuyen-dung'
    | '/uu-dai'
    | '/van-hoa-doanh-nghiep'
    | '/xo-so'
    | '/xoc-dia-bip'
    | '/xoc-dia-jun88'
  id:
    | '__root__'
    | '/'
    | '/baccarat-jun88'
    | '/baccarat-online'
    | '/bao-lo-la-gi'
    | '/blackjack-jun88'
    | '/cach-tinh-diem-lo'
    | '/casino'
    | '/casino-jun88'
    | '/chinh-sach-quyen-rieng-tu'
    | '/dang-ky-jun88'
    | '/dang-nhap-jun88'
    | '/dieu-khoan-dich-vu'
    | '/esport'
    | '/giai-den-lo-de'
    | '/gioi-thieu'
    | '/khuyen-mai'
    | '/lien-he-jun88'
    | '/lien-he-voi-chung-toi'
    | '/nap-tien-jun88'
    | '/no-hu'
    | '/poker-jun88'
    | '/poker-online'
    | '/rake-la-gi-trong-poker'
    | '/rong-ho-jun88'
    | '/rong-ho-online'
    | '/roulette-jun88'
    | '/rut-tien-jun88'
    | '/sitemap.xml'
    | '/su-kien'
    | '/tai-app-jun88'
    | '/tai-xiu'
    | '/tai-xiu-jun88'
    | '/the-thao'
    | '/tuyen-dung'
    | '/uu-dai'
    | '/van-hoa-doanh-nghiep'
    | '/xo-so'
    | '/xoc-dia-bip'
    | '/xoc-dia-jun88'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaccaratJun88Route: typeof BaccaratJun88Route
  BaccaratOnlineRoute: typeof BaccaratOnlineRoute
  BaoLoLaGiRoute: typeof BaoLoLaGiRoute
  BlackjackJun88Route: typeof BlackjackJun88Route
  CachTinhDiemLoRoute: typeof CachTinhDiemLoRoute
  CasinoRoute: typeof CasinoRoute
  CasinoJun88Route: typeof CasinoJun88Route
  ChinhSachQuyenRiengTuRoute: typeof ChinhSachQuyenRiengTuRoute
  DangKyJun88Route: typeof DangKyJun88Route
  DangNhapJun88Route: typeof DangNhapJun88Route
  DieuKhoanDichVuRoute: typeof DieuKhoanDichVuRoute
  EsportRoute: typeof EsportRoute
  GiaiDenLoDeRoute: typeof GiaiDenLoDeRoute
  GioiThieuRoute: typeof GioiThieuRoute
  KhuyenMaiRoute: typeof KhuyenMaiRoute
  LienHeJun88Route: typeof LienHeJun88Route
  LienHeVoiChungToiRoute: typeof LienHeVoiChungToiRoute
  NapTienJun88Route: typeof NapTienJun88Route
  NoHuRoute: typeof NoHuRoute
  PokerJun88Route: typeof PokerJun88Route
  PokerOnlineRoute: typeof PokerOnlineRoute
  RakeLaGiTrongPokerRoute: typeof RakeLaGiTrongPokerRoute
  RongHoJun88Route: typeof RongHoJun88Route
  RongHoOnlineRoute: typeof RongHoOnlineRoute
  RouletteJun88Route: typeof RouletteJun88Route
  RutTienJun88Route: typeof RutTienJun88Route
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuKienRoute: typeof SuKienRoute
  TaiAppJun88Route: typeof TaiAppJun88Route
  TaiXiuRoute: typeof TaiXiuRoute
  TaiXiuJun88Route: typeof TaiXiuJun88Route
  TheThaoRoute: typeof TheThaoRoute
  TuyenDungRoute: typeof TuyenDungRoute
  UuDaiRoute: typeof UuDaiRoute
  VanHoaDoanhNghiepRoute: typeof VanHoaDoanhNghiepRoute
  XoSoRoute: typeof XoSoRoute
  XocDiaBipRoute: typeof XocDiaBipRoute
  XocDiaJun88Route: typeof XocDiaJun88Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xoc-dia-jun88': {
      id: '/xoc-dia-jun88'
      path: '/xoc-dia-jun88'
      fullPath: '/xoc-dia-jun88'
      preLoaderRoute: typeof XocDiaJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xoc-dia-bip': {
      id: '/xoc-dia-bip'
      path: '/xoc-dia-bip'
      fullPath: '/xoc-dia-bip'
      preLoaderRoute: typeof XocDiaBipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xo-so': {
      id: '/xo-so'
      path: '/xo-so'
      fullPath: '/xo-so'
      preLoaderRoute: typeof XoSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/van-hoa-doanh-nghiep': {
      id: '/van-hoa-doanh-nghiep'
      path: '/van-hoa-doanh-nghiep'
      fullPath: '/van-hoa-doanh-nghiep'
      preLoaderRoute: typeof VanHoaDoanhNghiepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uu-dai': {
      id: '/uu-dai'
      path: '/uu-dai'
      fullPath: '/uu-dai'
      preLoaderRoute: typeof UuDaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuyen-dung': {
      id: '/tuyen-dung'
      path: '/tuyen-dung'
      fullPath: '/tuyen-dung'
      preLoaderRoute: typeof TuyenDungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-thao': {
      id: '/the-thao'
      path: '/the-thao'
      fullPath: '/the-thao'
      preLoaderRoute: typeof TheThaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-xiu-jun88': {
      id: '/tai-xiu-jun88'
      path: '/tai-xiu-jun88'
      fullPath: '/tai-xiu-jun88'
      preLoaderRoute: typeof TaiXiuJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-xiu': {
      id: '/tai-xiu'
      path: '/tai-xiu'
      fullPath: '/tai-xiu'
      preLoaderRoute: typeof TaiXiuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-app-jun88': {
      id: '/tai-app-jun88'
      path: '/tai-app-jun88'
      fullPath: '/tai-app-jun88'
      preLoaderRoute: typeof TaiAppJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/su-kien': {
      id: '/su-kien'
      path: '/su-kien'
      fullPath: '/su-kien'
      preLoaderRoute: typeof SuKienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rut-tien-jun88': {
      id: '/rut-tien-jun88'
      path: '/rut-tien-jun88'
      fullPath: '/rut-tien-jun88'
      preLoaderRoute: typeof RutTienJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roulette-jun88': {
      id: '/roulette-jun88'
      path: '/roulette-jun88'
      fullPath: '/roulette-jun88'
      preLoaderRoute: typeof RouletteJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rong-ho-online': {
      id: '/rong-ho-online'
      path: '/rong-ho-online'
      fullPath: '/rong-ho-online'
      preLoaderRoute: typeof RongHoOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rong-ho-jun88': {
      id: '/rong-ho-jun88'
      path: '/rong-ho-jun88'
      fullPath: '/rong-ho-jun88'
      preLoaderRoute: typeof RongHoJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rake-la-gi-trong-poker': {
      id: '/rake-la-gi-trong-poker'
      path: '/rake-la-gi-trong-poker'
      fullPath: '/rake-la-gi-trong-poker'
      preLoaderRoute: typeof RakeLaGiTrongPokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poker-online': {
      id: '/poker-online'
      path: '/poker-online'
      fullPath: '/poker-online'
      preLoaderRoute: typeof PokerOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poker-jun88': {
      id: '/poker-jun88'
      path: '/poker-jun88'
      fullPath: '/poker-jun88'
      preLoaderRoute: typeof PokerJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-hu': {
      id: '/no-hu'
      path: '/no-hu'
      fullPath: '/no-hu'
      preLoaderRoute: typeof NoHuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nap-tien-jun88': {
      id: '/nap-tien-jun88'
      path: '/nap-tien-jun88'
      fullPath: '/nap-tien-jun88'
      preLoaderRoute: typeof NapTienJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he-voi-chung-toi': {
      id: '/lien-he-voi-chung-toi'
      path: '/lien-he-voi-chung-toi'
      fullPath: '/lien-he-voi-chung-toi'
      preLoaderRoute: typeof LienHeVoiChungToiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he-jun88': {
      id: '/lien-he-jun88'
      path: '/lien-he-jun88'
      fullPath: '/lien-he-jun88'
      preLoaderRoute: typeof LienHeJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khuyen-mai': {
      id: '/khuyen-mai'
      path: '/khuyen-mai'
      fullPath: '/khuyen-mai'
      preLoaderRoute: typeof KhuyenMaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giai-den-lo-de': {
      id: '/giai-den-lo-de'
      path: '/giai-den-lo-de'
      fullPath: '/giai-den-lo-de'
      preLoaderRoute: typeof GiaiDenLoDeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esport': {
      id: '/esport'
      path: '/esport'
      fullPath: '/esport'
      preLoaderRoute: typeof EsportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieu-khoan-dich-vu': {
      id: '/dieu-khoan-dich-vu'
      path: '/dieu-khoan-dich-vu'
      fullPath: '/dieu-khoan-dich-vu'
      preLoaderRoute: typeof DieuKhoanDichVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap-jun88': {
      id: '/dang-nhap-jun88'
      path: '/dang-nhap-jun88'
      fullPath: '/dang-nhap-jun88'
      preLoaderRoute: typeof DangNhapJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky-jun88': {
      id: '/dang-ky-jun88'
      path: '/dang-ky-jun88'
      fullPath: '/dang-ky-jun88'
      preLoaderRoute: typeof DangKyJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-quyen-rieng-tu': {
      id: '/chinh-sach-quyen-rieng-tu'
      path: '/chinh-sach-quyen-rieng-tu'
      fullPath: '/chinh-sach-quyen-rieng-tu'
      preLoaderRoute: typeof ChinhSachQuyenRiengTuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino-jun88': {
      id: '/casino-jun88'
      path: '/casino-jun88'
      fullPath: '/casino-jun88'
      preLoaderRoute: typeof CasinoJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino': {
      id: '/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof CasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cach-tinh-diem-lo': {
      id: '/cach-tinh-diem-lo'
      path: '/cach-tinh-diem-lo'
      fullPath: '/cach-tinh-diem-lo'
      preLoaderRoute: typeof CachTinhDiemLoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blackjack-jun88': {
      id: '/blackjack-jun88'
      path: '/blackjack-jun88'
      fullPath: '/blackjack-jun88'
      preLoaderRoute: typeof BlackjackJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-lo-la-gi': {
      id: '/bao-lo-la-gi'
      path: '/bao-lo-la-gi'
      fullPath: '/bao-lo-la-gi'
      preLoaderRoute: typeof BaoLoLaGiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baccarat-online': {
      id: '/baccarat-online'
      path: '/baccarat-online'
      fullPath: '/baccarat-online'
      preLoaderRoute: typeof BaccaratOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baccarat-jun88': {
      id: '/baccarat-jun88'
      path: '/baccarat-jun88'
      fullPath: '/baccarat-jun88'
      preLoaderRoute: typeof BaccaratJun88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaccaratJun88Route: BaccaratJun88Route,
  BaccaratOnlineRoute: BaccaratOnlineRoute,
  BaoLoLaGiRoute: BaoLoLaGiRoute,
  BlackjackJun88Route: BlackjackJun88Route,
  CachTinhDiemLoRoute: CachTinhDiemLoRoute,
  CasinoRoute: CasinoRoute,
  CasinoJun88Route: CasinoJun88Route,
  ChinhSachQuyenRiengTuRoute: ChinhSachQuyenRiengTuRoute,
  DangKyJun88Route: DangKyJun88Route,
  DangNhapJun88Route: DangNhapJun88Route,
  DieuKhoanDichVuRoute: DieuKhoanDichVuRoute,
  EsportRoute: EsportRoute,
  GiaiDenLoDeRoute: GiaiDenLoDeRoute,
  GioiThieuRoute: GioiThieuRoute,
  KhuyenMaiRoute: KhuyenMaiRoute,
  LienHeJun88Route: LienHeJun88Route,
  LienHeVoiChungToiRoute: LienHeVoiChungToiRoute,
  NapTienJun88Route: NapTienJun88Route,
  NoHuRoute: NoHuRoute,
  PokerJun88Route: PokerJun88Route,
  PokerOnlineRoute: PokerOnlineRoute,
  RakeLaGiTrongPokerRoute: RakeLaGiTrongPokerRoute,
  RongHoJun88Route: RongHoJun88Route,
  RongHoOnlineRoute: RongHoOnlineRoute,
  RouletteJun88Route: RouletteJun88Route,
  RutTienJun88Route: RutTienJun88Route,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuKienRoute: SuKienRoute,
  TaiAppJun88Route: TaiAppJun88Route,
  TaiXiuRoute: TaiXiuRoute,
  TaiXiuJun88Route: TaiXiuJun88Route,
  TheThaoRoute: TheThaoRoute,
  TuyenDungRoute: TuyenDungRoute,
  UuDaiRoute: UuDaiRoute,
  VanHoaDoanhNghiepRoute: VanHoaDoanhNghiepRoute,
  XoSoRoute: XoSoRoute,
  XocDiaBipRoute: XocDiaBipRoute,
  XocDiaJun88Route: XocDiaJun88Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
